name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static llvm lld clang

    - name: Get Perf
      run: curl -Lo copybins/perf https://github.com/HoolockLinux/HoolockRD/releases/download/perf/perf

    - name: Build
      run: sudo ./build.sh

    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: initramfs.gz
        name: initramfs.gz

    - name: Setup Alpine ARM64 sysroot
      run: |
        sudo apt-get install -y qemu-user-static
        wget https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/aarch64/alpine-minirootfs-3.19.0-aarch64.tar.gz
        mkdir alpine-sysroot
        sudo tar xf alpine-minirootfs-3.19.0-aarch64.tar.gz -C alpine-sysroot/
        sudo cp /usr/bin/qemu-aarch64-static alpine-sysroot/usr/bin/

    - name: Install VNC + WM packages
      run: |
        sudo chroot alpine-sysroot/ /bin/sh -c "
          apk add --no-cache \
            tigervnc \
            openbox \
            xterm \
            font-misc-misc \
            libx11 libxext libxfixes libxi libxrandr
    "
